[package]
name = "crab_snake"
version = "0.1.0"
authors = ["v0idpwn <v0idpwn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33"
rand = "0.7.3"
